name: Compare functions
on: push
jobs:
    compare:
        runs-on: ubuntu-latest
        steps:
            - run: printenv | grep '_FUNC'
              env:
                CONTAINS_FUNC: ${{ contains('HELLO', 'LLO') }}
                STARTS_WITH_FUNC: ${{ startsWith('HELLO', 'HE') }}
                ENDS_WITH_FUNC: ${{ endsWith('HELLO', 'lo') }}
